"""initial_migration

Revision ID: 310a33eb7bc2
Revises: 
Create Date: 2026-04-23 23:46:06.542821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310a33eb7bc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_entry_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('maiden_name', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('died_in_ww2', sa.Boolean(), nullable=True),
    sa.Column('death_date', sa.Date(), nullable=True),
    sa.Column('death_place', sa.String(), nullable=True),
    sa.Column('death_cause', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('mother_maiden_name', sa.String(), nullable=True),
    sa.Column('spouse_name', sa.String(), nullable=True),
    sa.Column('spouse_maiden_name', sa.String(), nullable=True),
    sa.Column('children_names', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_external_entry_id'), ['external_entry_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_persons_full_name'), ['full_name'], unique=False)

    op.create_table('statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deportations_and_repressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('other_information', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('military_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('other_military_service', sa.String(), nullable=True),
    sa.Column('participation_in_wwii_battles', sa.String(), nullable=True),
    sa.Column('medals_received', sa.String(), nullable=True),
    sa.Column('other_battles', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('occupation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('city_place', sa.String(), nullable=True),
    sa.Column('nearest_large_city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_military_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('orphanages', sa.String(), nullable=True),
    sa.Column('civilian_camp_middle_east', sa.String(), nullable=True),
    sa.Column('civilian_camp_india', sa.String(), nullable=True),
    sa.Column('civilian_camp_africa', sa.String(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal_situation_outbreak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('residence', sa.String(), nullable=True),
    sa.Column('kresy_inhabitant_status', sa.String(), nullable=True),
    sa.Column('ethnicity', sa.String(), nullable=True),
    sa.Column('religion', sa.String(), nullable=True),
    sa.Column('education_level', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=True),
    sa.Column('military_status', sa.String(), nullable=True),
    sa.Column('military_rank', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related_galleries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('url_text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repatriations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('locality', sa.String(), nullable=True),
    sa.Column('nearest_large_city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('url_text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('military_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('military_experience_id', sa.Integer(), nullable=False),
    sa.Column('service_branch', sa.String(), nullable=True),
    sa.Column('unit_name', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=True),
    sa.Column('from_when_date', sa.Date(), nullable=True),
    sa.Column('to_when_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['military_experience_id'], ['military_experiences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deportation_id', sa.Integer(), nullable=False),
    sa.Column('from_when_date', sa.Date(), nullable=True),
    sa.Column('to_when_date', sa.Date(), nullable=True),
    sa.Column('deporting_authority', sa.String(), nullable=True),
    sa.Column('oblast', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['deportation_id'], ['deportations_and_repressions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places')
    op.drop_table('military_services')
    op.drop_table('sources')
    op.drop_table('repatriations')
    op.drop_table('related_galleries')
    op.drop_table('personal_situation_outbreak')
    op.drop_table('other_military_experiences')
    op.drop_table('occupation_periods')
    op.drop_table('military_experiences')
    op.drop_table('deportations_and_repressions')
    op.drop_table('statuses')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_full_name'))
        batch_op.drop_index(batch_op.f('ix_persons_external_entry_id'))

    op.drop_table('persons')
    # ### end Alembic commands ###
